services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: backend
      target: develop
    ports:
      - 5268:5268
    depends_on:
      - database
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
    environment:
      # Intentionally public; this file is for LOCAL builds only.
      Authorization__Audience: "Audience"
      Authorization__Issuer: "Issuer"
      Authorization__Token: "TestOnlyIntentionallyPublic111111111111111111111111111111111111111111111111111111111111111111111111111111111111111111"
      ConnectionStrings__Database: Host=database;Username=postgres;Password=password;Database=postgres

  migrate:
    scale: 0
    build:
      context: backend
      target: migrate
    depends_on:
      - database
    environment:
      # Intentionally public; this file is for LOCAL builds only.
      AdminPassword: admin
      ConnectionStrings__Database: Host=database;Username=postgres;Password=password;Database=postgres

  frontend:
    build:
      context: frontend
      target: develop
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      BACKEND_URL: http://host.docker.internal:5268
      NEXT_TELEMETRY_DISABLED: 1
