services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: backend
      target: production
    ports:
      - 5268:5268
    depends_on:
      - database
    environment:
      # Intentionally public; this file is for LOCAL production build
      AdminPassword: admin
      ConnectionStrings__Database: Host=database;Username=postgres;Password=password;Database=postgres

  migrate:
    scale: 0
    build:
      context: backend
      target: migrate
    depends_on:
      - database

  frontend:
    build:
      context: frontend
      target: production
    ports:
      - 3000:3000
    environment:
      NEXT_TELEMETRY_DISABLED: 1
