services:
  backend:
    build:
      context: backend
    ports:
      - 5268:5268
    develop:
      watch:
        - action: sync
          path: ./backend
          target: /app
  frontend:
    build:
      context: frontend
    ports:
      - 3000:3000
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /app
    environment:
      NEXT_TELEMETRY_DISABLED: 1
