services:
  database:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password

  backend:
    build:
      context: backend
      target: develop
    ports:
      - 5268:5268
    depends_on:
      - database
    # environment:
    #   # Intentionally public; for local production build
    #   - ADMIN_PASSWORD: admin

  frontend:
    build:
      context: frontend
      target: production
    ports:
      - 3000:3000
    environment:
      NEXT_TELEMETRY_DISABLED: 1
