@SkillBank_HostAddress = http://localhost:5268
@accessToken = {{login.response.body.$.accessToken}}

### Authenticate

# @name login
POST {{SkillBank_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "developer",
  "password": "developer"
}

### Get current user details

GET {{SkillBank_HostAddress}}/api/Users/current
Accept: application/json
Authorization: Bearer {{accessToken}}

### Update current user details

PUT {{SkillBank_HostAddress}}/api/Users/current
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "skills": [
    {
      "label": ".Net"
    },
    {
      "label": "ASP.NET"
    }
  ]
}

### Get all skills

GET {{SkillBank_HostAddress}}/api/Skills
Accept: application/json
Authorization: Bearer {{accessToken}}
