@SkillBank_HostAddress = http://localhost:5268
@accessToken = {{login.response.body.$.accessToken}}
@refreshToken = {{login.response.body.$.refreshToken}}
@createdUser = {{create.response.body.$.id}}

### Authenticate

# @name login
POST {{SkillBank_HostAddress}}/api/Auth/login
Content-Type: application/json

{
  "username": "admin",
  "password": "admin"
}

### Refresh

# @name login
POST {{SkillBank_HostAddress}}/api/Auth/refresh
Content-Type: application/json
Authorization: Bearer {{refreshToken}}

### Revoke

POST {{SkillBank_HostAddress}}/api/Auth/revoke
Content-Type: application/json
Authorization: Bearer {{accessToken}}

### Create user (admin only)

# @name create
POST {{SkillBank_HostAddress}}/api/Users
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "username": "junior",
  "password": "junior",
  "role": "Consultant"
}

### Get created user details

GET {{SkillBank_HostAddress}}/api/Users/{{createdUser}}
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get all users

GET {{SkillBank_HostAddress}}/api/Users
Accept: application/json
Authorization: Bearer {{accessToken}}

### Get all consultants

POST {{SkillBank_HostAddress}}/api/Consultants
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "skills": [
    {
      "label": "JavaScript",
      "minimumExperience": 2
    },
    {
      "label": "React"
    }
  ]
}

### Get current user details

GET {{SkillBank_HostAddress}}/api/Users/current
Accept: application/json
Authorization: Bearer {{accessToken}}

### Update current user details

PUT {{SkillBank_HostAddress}}/api/Users/current
Content-Type: application/json
Authorization: Bearer {{accessToken}}

{
  "skills": [
    {
      "label": ".Net",
      "proficiency": 4
    },
    {
      "label": "ASP.NET",
      "proficiency": 3
    }
  ]
}

### Get all skills

GET {{SkillBank_HostAddress}}/api/Skills
Accept: application/json
Authorization: Bearer {{accessToken}}
