name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/skillbank-backend:${{ github.sha }}
          target: production

      - name: Build migrations
        run: |
          dotnet restore
          dotnet tool install --global dotnet-ef
          dotnet ef migrations bundle --project SkillBank

      - name: Run migrations
        run: ./efbundle
        env:
          AdminPassword: ${{ secrets.ADMIN_PASSWORD }}
          DOTNET_ENVIRONMENT: Production
          ConnectionStrings__Database: ${{ secrets.DB_CONNECTION_STRING }}

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: skillbank-backend
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/skillbank-backend:${{ github.sha }}
