name: .NET

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

  publish:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./backend

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x

      - name: Build migrations
        run: |
          dotnet restore
          dotnet tool install --global dotnet-ef
          dotnet ef migrations bundle --project SkillBank

      - name: Run migrations
        run: ./efbundle
        env:
          ADMIN_PASSWORD: ${{ secrets.ADMIN_PASSWORD }}
          DOTNET_ENVIRONMENT: Production
          ConnectionStrings__Database: ${{ secrets.DB_CONNECTION_STRING }}
