name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Restore dependencies
        run: npm ci

      - name: Check formatting
        run: |
          npm run lint
          npm run check-format

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and push image
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
      - run: |
          docker build --target production -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/skillbank-frontend${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/skillbank-frontend${{ github.sha }}

      - name: Deploy to Azure Container Apps
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/skillbank-frontend${{ github.sha }}
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}
          containerAppName: skillbank
