name: Node.js CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NEXT_TELEMETRY_DISABLED: 1

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./frontend

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Restore dependencies
        run: npm ci

      - name: Check formatting
        run: |
          npm run lint
          npm run check-format

      - name: Build
        run: npm run build

      - name: Run tests
        run: npm test

  publish:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/master'

    steps:
      - uses: actions/checkout@v4

      - name: Login to docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and publish
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.REGISTRY_LOGIN_SERVER }}/skillbank-frontend:${{ github.sha }}
          target: production

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy
        uses: azure/webapps-deploy@v2
        with:
          app-name: skillbank
          images: ${{ secrets.REGISTRY_LOGIN_SERVER }}/skillbank-frontend:${{ github.sha }}
